(put 'customize-group 'disabled nil)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-engine 'XeLatex)
 '(TeX-engine-alist '((XeLatex "XeLatex" "xetex" "xelatex" "context")))
 '(alert-default-style 'notifier)
 '(connection-local-criteria-alist
   '(((:application vc-git) vc-git-connection-default-profile)
     ((:application eshell :protocol "sshx" :machine "lf2")
      autogenerated-connection-local-profile/\(:application\ eshell\ :protocol\ \"sshx\"\ :machine\ \"lf2\"\))
     ((:application tramp :protocol "flatpak")
      tramp-flatpak-connection-local-default-profile)
     ((:application tramp :protocol "kubernetes")
      tramp-kubernetes-connection-local-default-profile)
     ((:application tramp :machine "localhost")
      tramp-connection-local-darwin-ps-profile)
     ((:application tramp :machine "C02F72GKMD6R")
      tramp-connection-local-darwin-ps-profile)
     ((:application tramp) tramp-connection-local-default-system-profile
      tramp-connection-local-default-shell-profile)
     ((:application eshell) eshell-connection-default-profile)))
 '(connection-local-profile-alist
   '((vc-git-connection-default-profile (vc-git--program-version))
     (autogenerated-connection-local-profile/\(:application\ eshell\ :protocol\ \"sshx\"\ :machine\ \"lf2\"\)
      (eshell-path-env-list "/bin" "/usr/bin" "/sbin" "/usr/sbin"
                            "/usr/local/bin" "/usr/local/sbin"))
     (tramp-flatpak-connection-local-default-profile
      (tramp-remote-path "/app/bin" tramp-default-remote-path "/bin" "/usr/bin"
                         "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"
                         "/local/bin" "/local/freeware/bin" "/local/gnu/bin"
                         "/usr/freeware/bin" "/usr/pkg/bin" "/usr/contrib/bin"
                         "/opt/bin" "/opt/sbin" "/opt/local/bin"))
     (tramp-kubernetes-connection-local-default-profile
      (tramp-config-check . tramp-kubernetes--current-context-data)
      (tramp-extra-expand-args 97
                               (tramp-kubernetes--container
                                (car tramp-current-connection))
                               104
                               (tramp-kubernetes--pod
                                (car tramp-current-connection))
                               120
                               (tramp-kubernetes--context-namespace
                                (car tramp-current-connection))))
     (tramp-connection-local-darwin-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o"
                                        "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                        "-o" "state=abcde" "-o"
                                        "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args")
      (tramp-process-attributes-ps-format (pid . number) (euid . number)
                                          (user . string) (egid . number)
                                          (comm . 52) (state . 5)
                                          (ppid . number) (pgrp . number)
                                          (sess . number) (ttname . string)
                                          (tpgid . number) (minflt . number)
                                          (majflt . number)
                                          (time . tramp-ps-time) (pri . number)
                                          (nice . number) (vsize . number)
                                          (rss . number) (etime . tramp-ps-time)
                                          (pcpu . number) (pmem . number) (args)))
     (tramp-connection-local-busybox-ps-profile
      (tramp-process-attributes-ps-args "-o"
                                        "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                        "-o" "stat=abcde" "-o"
                                        "ppid,pgid,tty,time,nice,etime,args")
      (tramp-process-attributes-ps-format (pid . number) (user . string)
                                          (group . string) (comm . 52)
                                          (state . 5) (ppid . number)
                                          (pgrp . number) (ttname . string)
                                          (time . tramp-ps-time) (nice . number)
                                          (etime . tramp-ps-time) (args)))
     (tramp-connection-local-bsd-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o"
                                        "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                        "-o"
                                        "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args")
      (tramp-process-attributes-ps-format (pid . number) (euid . number)
                                          (user . string) (egid . number)
                                          (group . string) (comm . 52)
                                          (state . string) (ppid . number)
                                          (pgrp . number) (sess . number)
                                          (ttname . string) (tpgid . number)
                                          (minflt . number) (majflt . number)
                                          (time . tramp-ps-time) (pri . number)
                                          (nice . number) (vsize . number)
                                          (rss . number) (etime . number)
                                          (pcpu . number) (pmem . number) (args)))
     (tramp-connection-local-default-shell-profile (shell-file-name . "/bin/sh")
      (shell-command-switch . "-c"))
     (tramp-connection-local-default-system-profile (path-separator . ":")
      (null-device . "/dev/null"))
     (eshell-connection-default-profile (eshell-path-env-list))))
 '(consult-narrow-key "<")
 '(custom-safe-themes
   '("02f57ef0a20b7f61adce51445b68b2a7e832648ce2e7efb19d217b6454c1b644"
     "afa47084cb0beb684281f480aa84dab7c9170b084423c7f87ba755b15f6776ef"
     "00cec71d41047ebabeb310a325c365d5bc4b7fab0a681a2a108d32fb161b4006"
     "835868dcd17131ba8b9619d14c67c127aa18b90a82438c8613586331129dda63"
     "0466adb5554ea3055d0353d363832446cd8be7b799c39839f387abb631ea0995"
     "4f1d2476c290eaa5d9ab9d13b60f2c0f1c8fa7703596fa91b235db7f99a9441b"
     "246a9596178bb806c5f41e5b571546bb6e0f4bd41a9da0df5dfbca7ec6e2250c"
     "333958c446e920f5c350c4b4016908c130c3b46d590af91e1e7e2a0611f1e8c5"
     "8146edab0de2007a99a2361041015331af706e7907de9d6a330a3493a541e5a6"
     "745d03d647c4b118f671c49214420639cb3af7152e81f132478ed1c649d4597d"
     "c2aeb1bd4aa80f1e4f95746bda040aafb78b1808de07d340007ba898efa484f5" default))
 '(dap-python-debugger 'debugpy)
 '(denote-directory "~/org/notes")
 '(denote-journal-extras-title-format "%Y-%m-w%0W-q%q")
 '(denote-silo-extras-directories '("~/org/notes" "~/org/journal"))
 '(dtrt-indent-min-offset 4)
 '(evil-collection-setup-minibuffer t)
 '(evil-shift-width 2)
 '(flycheck-clang-language-standard "c++17")
 '(flycheck-gcc-language-standard "c++17")
 '(grep-command "ggrep")
 '(ispell-grep-command "ggrep")
 '(lsp-bridge-python-command "python3")
 '(lsp-bridge-remote-python-command "python3.12")
 '(lsp-bridge-remote-python-file
   "~/.config/emacs/.local/straight/repos/lsp-bridge/lsp_bridge.py")
 '(lsp-bridge-remote-start-automatically t)
 '(lsp-ui-imenu-buffer-position 'left)
 '(magit-todos-insert-after '(bottom) nil nil "Changed by setter of obsolete option `magit-todos-insert-at'")
 '(mind-wave-api-key-path "~/.emacs.d/.local/mind-wave/chatgpt_api_key.txt")
 '(org-M-RET-may-split-line t)
 '(org-agenda-files '("~/org/" "~/org/journal" "~/org/notes" "~/org/roam"))
 '(org-export-with-sub-superscripts '{})
 '(org-hide-emphasis-markers t)
 '(org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
 '(org-journal-dir "~/org/notes/journal/")
 '(org-journal-file-format "%Y%m%dT080000--%Y-%m-w%0W-q%q__journal_org.org")
 '(org-journal-file-header
   "#+title:      %Y-%m-w%0W-q%q\12#+date:       [%Y-%m-%d %b 08:00]\12#+filetags:   :journal:org:\12#+identifier: %Y%m%dT080000")
 '(org-journal-file-type 'weekly)
 '(org-journal-time-prefix "** TODO ")
 '(org-latex-compiler "xelatex")
 '(org-latex-hyperref-template
   "\\hypersetup{\12 pdfauthor={%a},\12 pdftitle={%t},\12 pdfkeywords={%k},\12 pdfsubject={%d},\12 pdfcreator={%c}, \12 pdflang={%L},\12 colorlinks=true}")
 '(org-margin-headers-set 'H-svg)
 '(org-modern-hide-stars 'leading)
 '(org-pomodoro-expiry-time 150)
 '(org-pomodoro-play-sounds nil)
 '(org-roam-database-connector 'sqlite-builtin)
 '(org-roam-directory "/Users/bytedance/org/roam/")
 '(org-super-agenda-groups '((:auto-group t)))
 '(org-tag-alist
   '((:startgrouptag) ("171release" . 114) (:grouptags) ("171qatest" . 113)
     ("171pipeline" . 112) ("171env" . 101) (:endgrouptag) (:startgrouptag)
     ("workoncrypto" . 99) (:grouptags) ("heshan" . 104) ("jingkai" . 106)
     ("nxu" . 120) ("yxj" . 121) (:endgrouptag)))
 '(org-todo-keywords
   '((sequence "TODO(t)" "TODAY(a)" "NEXT(x)" "PROJ(p)" "TASKGRP(g)" "LOOP(l)"
      "INITIATED(i)" "INPROGRESS(u)" "REVIEW(r)" "WAITING(w)" "HOLD(h)" "|"
      "DONE(d)" "CANCEL(c)" "KILL(k)" "IDEA(v)" "DRAFT(f)" "BACKLOG(b)"
      "NOTE(j)" "MOVED(m)" "SPLITTED(s)")
     (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)")
     (sequence "|" "OKAY(o)" "YES(y)" "NO(n)")))
 '(plantuml-default-exec-mode 'jar)
 '(plantuml-jar-args '("-charset" "UTF-8" "-DRELATIVE_INCLUDE=."))
 '(python-interpreter "python3.11")
 '(python-shell-interpreter "python3.11")
 '(pyvenv-virtualenvwrapper-python "/opt/homebrew/bin/python3.11")
 '(realgud:pdb-command-name "python3 -m pdb")
 '(safe-local-variable-values
   '((org-roam-db-location . "~/org/roam/coderead/tidb/org-roam.db")
     (org-roam-db-location . "~/org/roam/tidb/coderead/tidb/org-roam.db")
     (org-roam-db-location . "~/org/roam/tidb/coderead/org-roam.db")
     (org-roam-directory . "~/org/roam/coderead/tidb")
     (org-roam-db-location . "~/org/roam/mysql/org-roam.db")
     (org-roam-directory . "~/org/roam/mysql")
     (org-roam-db-location . "~/org/roam/tidb/org-roam.db")
     (org-roam-directory . "~/org/roam/tidb")))
 '(standard-indent 2)
 '(straight-vc-git-default-protocol 'ssh)
 '(tramp-default-method "sshx")
 '(tramp-default-method-alist
   '((nil "\\`\\(?:anonymous\\|ftp\\)\\'" "ftp") ("\\`ftp\\." nil "ftp")
     ("\\`\\(?:C02F72GKMD6R\\|\\(?:127\\.0\\.0\\.1\\|::1\\|localhost[46]?\\)\\)\\'"
      "\\`root\\'" "su")
     ("10.37.19.60" "ning.xu" "ssh")))
 '(tramp-remote-path
   '(tramp-default-remote-path "/bin" "/usr/bin" "/sbin" "/usr/sbin"
     "/usr/local/bin" "/usr/local/sbin" "/local/bin" "/local/freeware/bin"
     "/local/gnu/bin" "/usr/freeware/bin" "/usr/pkg/bin" "/usr/contrib/bin"
     "/opt/bin" "/opt/sbin" "/opt/local/bin" tramp-own-remote-path))
 '(warning-suppress-log-types '((lexical-binding)))
 '(xeft-default-extension "org")
 '(xeft-directory "~/org")
 '(xeft-recursive 'follow-symlinks))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-remark-highlighter ((t (:background "dark cyan" :underline (:color "dark cyan" :style wave :position nil)))))
 '(ts-fold-replacement-face ((t (:foreground nil :box nil :inherit font-lock-comment-face :weight light)))))
(put 'customize-variable 'disabled nil)
(put 'customize-face 'disabled nil)
(put 'projectile-ripgrep 'disabled nil)
;;; -*- lexical-binding: t -*-
